using System;
using System.Collections.Generic;
using Staffer.OrgChart.Layout.CSharp;

namespace Staffer.OrgChart.CSharp.Test.Layout
{
    /// <summary>
    /// Test data generator utility.
    /// </summary>
    public class TestDataGen
    {
        /// <summary>
        /// Adds some data items into supplied <paramref name="dataSource"/>.
        /// </summary>
        public void GenerateDataItems([NotNull] TestDataSource dataSource, int count)
        {
            foreach (var item in GenerateRandomDataItems(count))
            {
                dataSource.Items.Add(item.Id, item);
            }
        }

        private IEnumerable<TestDataItem> GenerateRandomDataItems(int itemCount)
        {
            if (itemCount < 0)
            {
                throw new ArgumentOutOfRangeException(nameof(itemCount), itemCount, "Count must be zero or positive");
            }

            var random = new Random(0);

            var items = new List<TestDataItem>(itemCount);
            for (var i = 0; i < itemCount; i++)
            {
                items.Add(new TestDataItem
                {
                    Id = i.ToString()
                });
            }

            var firstInLayer = 1;
            var prevLayerSize = 1;
            while (firstInLayer < itemCount)
            {
                var layerSize = prevLayerSize + random.Next(prevLayerSize * 2);
                for (var i = firstInLayer; i < firstInLayer + layerSize && i < itemCount; i++)
                {
                    var parentIndex = firstInLayer - 1 - random.Next(prevLayerSize);
                    items[i].ParentId = items[parentIndex].Id;
                }

                firstInLayer = firstInLayer + layerSize;
                prevLayerSize = layerSize;
            }

            foreach (var item in items)
            {
                yield return item;
            }
        }

        /// <summary>
        /// Some random box sizes.
        /// </summary>
        public static void GenerateBoxSizes([NotNull] BoxContainer boxContainer)
        {
            const int minWidth = 50;
            const int minHeight = 50;

            var random = new Random(Environment.TickCount);
            foreach (var box in boxContainer.BoxesById.Values)
            {
                if (box.IsAutoGenerated)
                {
                    box.Frame.Exterior = new Rect(new Size(minWidth, minHeight));
                }
                else
                {
                    box.Frame.Exterior = new Rect(new Size(minWidth + random.Next(40), minHeight + random.Next(10)));
                }
            }
        }
    }
}